import type { Project } from "../types/Project";

const PROJECTS: { [key: string]: Project } = {
  "multiverse": {
    "i18nKeys": {
      "name": "Playa: Multiverse",
      "description": "A socialy distanced and virtual 2020 simulation of what would happen on Playa",
      "company": "Celestial Bodies",
      "role": "Collaborator",
    },
    "year": 2020,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3",
    "thumbImgUrl": "/img/portfolio/multiverse/multiverse_thumb.jpg",
    "thumbAspectRatio": 0.9,
    "thumbVideoUrl": "/img/portfolio/multiverse/multiverse_thumb.mp4",
    "videoUrl": "https://youtu.be/niPZFy9t9b0",
    "liveDemoUrl": "https://multiverse.campcelestialbodies.org/"
  },
  "chatbot": {
    "i18nKeys": {
      "name": "AI Chatbot",
      "description": "A chatbot powered by the Large Language Model Qwen 2.5, by Alibaba Cloud",
      "company": "Personal Project",
      "role": "Full Stack / AI Engineer",
    },
    "year": 2025,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "Vue 3,Python,Hugging Face Transformers,LLMs,JavaScript,ES6,HTML5,CSS3",
    "thumbImgUrl": "/img/portfolio/chatbot/chatbot_thumb.png",
    "thumbAspectRatio": 1.15,
    "thumbVideoUrl": "/img/portfolio/chatbot/chatbot_thumb.mp4",
    "githubUrl": "https://github.com/jezzlucena/vue-ai-chatbot",
    "liveDemoUrl": "https://chatbot.jezzlucena.xyz/"
  },
  "climatempo": {
    "i18nKeys": {
      "name": "Climatempo",
      "description": "The leading weather forecast cross-platform app in Brazil",
      "company": "HXD Smart Solutions",
      "role": "Full Stack Engineer",
    },
    "year": 2012,
    "platforms": "Samsung SmartTV OS,LG SmartTV OS,Web",
    "stack": "JavaScript,XML,JSON,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/climatempo/climatempo_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/climatempo/climatempo_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/climatempo/climatempo_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097271/Climatempo-Weather-Forecast",
  },
  "dell": {
    "i18nKeys": {
      "name": "Dell Training Game",
      "description": "Dell's gamified experience to showcase their cutting-edge corporate server deployment application",
      "company": "Kaon Interactive",
      "role": "Full Stack Engineer",
    },
    "year": 2018,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "WebSockets,SQLite,JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/dell/dell_thumb.jpg",
    "thumbAspectRatio": 0.8,
    "thumbVideoUrl": "/img/portfolio/dell/dell_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/dell/dell_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097417/Dell-OME-Gamified-Experience",
    "videoUrl": "https://youtu.be/McDy33GSPUM",
    "liveDemoUrl": "https://demos.jezzlucena.com/DellOME"
  },
  "thermofisher": {
    "i18nKeys": {
      "name": "Precision Medicine",
      "description": "Thermo Fisher Scientific's Precision Medicine technology showcase app",
      "company": "Thermo Fisher",
      "role": "Full Stack Engineer",
    },
    "year": 2018,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/thermofisher/thermo_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/thermofisher/thermo_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/thermofisher/thermo_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097771/Thermo-Fisher-Precision-Medicine",
    "videoUrl": "https://youtu.be/JUgZ73YrFKs",
    "liveDemoUrl": "https://demos.jezzlucena.com/ThermoFisher_ADN"
  },
  "abbott": {
    "i18nKeys": {
      "name": "Abbott Transformation",
      "description": "B2B sales showcase for Abbott Diagnostics' Transformation laboratory solutions",
      "company": "Kaon Interactive",
      "role": "Front End Engineer",
    },
    "year": 2016,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n,Gather Content",
    "thumbImgUrl": "/img/portfolio/abbott/abbott_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/abbott/abbott_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/abbott/abbott_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74096955/Abbott-Transformation",
    "videoUrl": "https://youtu.be/CLGU7GhBO0k",
    "liveDemoUrl": "https://demos.jezzlucena.com/Transformation_ADN"
  },
  "strikeapose": {
    "i18nKeys": {
      "name": "Strike A Pose",
      "description": "A dystopian rhythm action-adventure video game, but make it fashion",
      "company": "Personal Project",
      "role": "Game Designer and Engineer",
    },
    "year": 2020,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,Heroku",
    "thumbImgUrl": "/img/portfolio/strikeapose/strikeapose_thumb.jpg",
    "thumbAspectRatio": 0.74,
    "thumbVideoUrl": "/img/portfolio/strikeapose/strikeapose_thumb.mp4",
    "videoUrl": "https://youtu.be/zbpl4O8iWtE"
  },
  "kaon": {
    "i18nKeys": {
      "name": "Kaon.com",
      "description": "Kaon creates advanced software technology and platforms to enable global companies to simplify their complex stories at every customer touch-point",
      "company": "Kaon Interactive",
      "role": "Senior Full Stack Engineer",
    },
    "year": 2017,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "Ruby on Rails,MongoDB,JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/kaon/kaon_thumb.jpg",
    "thumbAspectRatio": 1.15,
    "thumbVideoUrl": "/img/portfolio/kaon/kaon_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/kaon/kaon_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74096433/Kaoncom",
    "videoUrl": "https://youtu.be/2RX7FPld2lI",
    "liveDemoUrl": "http://www.kaon.com/"
  },
  "dxma": {
    "i18nKeys": {
      "name": "DxMA Awards 2016",
      "description": "The digital catalog for DxMA's best B2B apps award ceremony",
      "company": "Kaon Interactive",
      "role": "Full Stack Engineer",
    },
    "year": 2016,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/dxma/dxma_thumb.jpg",
    "thumbAspectRatio": 1.74,
    "thumbVideoUrl": "/img/portfolio/dxma/dxma_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/dxma/dxma_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097473/DxMA-Awards-Catalog",
    "videoUrl": "https://youtu.be/aQ6I_z8w9vo",
    "liveDemoUrl": "https://demos.jezzlucena.com/DxMA_2016"
  },
  "f5": {
    "i18nKeys": {
      "name": "F5 Hybrid Cloud",
      "description": "A showcase app for F5 Networks' best practices on cloud computing and security",
      "company": "Kaon Interactive",
      "role": "Full Stack Engineer",
    },
    "year": 2016,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/f5/f5_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/f5/f5_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/f5/f5_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097513/F5-Hybrid-Cloud",
    "videoUrl": "https://youtu.be/Bp1X9JAe0VE",
    "liveDemoUrl": "https://demos.jezzlucena.com/F5_ADN"
  },
  "hyundai": {
    "i18nKeys": {
      "name": "Hyundai HB20s",
      "description": "Hyundai's marketing app for the launch of HB20 and HB20s new models in Brazil",
      "company": "HXD Smart Solutions",
      "role": "Full Stack Engineer",
    },
    "year": 2013,
    "platforms": "Samsung SmartTV OS,LG SmartTV OS,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/hyundai/hyundai_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/hyundai/hyundai_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/hyundai/hyundai_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097571/Hyundai-HB20s-Launch",
  },
  "photobooth": {
    "i18nKeys": {
      "name": "Photobooth",
      "description": "A web application that snaps a picture when you smile. Machine Learning, AI, and Material Design included",
      "company": "Personal Project",
      "role": "Designer / AI Engineer",
    },
    "year": 2019,
    "platforms": "iOS,Android,Desktop,Web",
    "stack": "JavaScript,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/photobooth/photobooth_thumb.jpg",
    "thumbAspectRatio": 0.74,
    "thumbVideoUrl": "/img/portfolio/photobooth/photobooth_thumb.mp4",
    "videoUrl": "https://youtu.be/N8bxdOAP8Aw",
    "githubUrl": "https://github.com/jezzlucena/face-api-photobooth",
    "liveDemoUrl": "https://photobooth.jezzlucena.com"
  },
  "haystack": {
    "i18nKeys": {
      "name": "In a Haystack",
      "description": "A graduate thesis proof-of-concept video game project implementation",
      "company": "projects.companies.wpi",
      "role": "Game Designer and Engineer",
    },
    "year": 2016,
    "platforms": "Desktop,Web,iOS",
    "stack": "RPGMaker MV Script,Game Design,JavaScript,JSON,ES6,i18n",
    "thumbImgUrl": "/img/portfolio/in-a-haystack/haystack_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/in-a-haystack/haystack_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/in-a-haystack/haystack_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097641/In-a-Haystack",
    "liveDemoUrl": "https://demos.jezzlucena.com/In_a_Haystack"
  },
  "cocacola": {
    "i18nKeys": {
      "name": "Coca-Cola FM",
      "description": "Coca-Cola FM's official Smart TV app in Latin America",
      "company": "HXD Smart Solutions",
      "role": "Software Engineer",
    },
    "year": 2012,
    "platforms": "LG SmartTV OS,Web",
    "stack": "ActionScript 3,XML,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/coca-cola/coca_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/coca-cola/coca_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/coca-cola/coca_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097365/Coca-Cola-FM",
  },
  "pong4x": {
    "i18nKeys": {
      "name": "Pong! 4X",
      "description": "Proof-of-concept computer game that takes the classic Pong to a whole new hectic multiplayer experience",
      "company": "Personal Project",
      "role": "Game Designer and Engineer",
    },
    "year": 2014,
    "platforms": "Desktop",
    "stack": "Processing 3,Game Design,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/pong-4x/pong4x_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/pong-4x/pong4x_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/pong-4x/pong4x_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097689/Pong-4X",
    "githubUrl": "https://github.com/jezzlucena/pong_4x",
    "liveDemoUrl": "https://demos.jezzlucena.com/Pong_4X"
  },
  "bandip": {
    "i18nKeys": {
      "name": "Band IP",
      "description": "Band TV's leading video-on-demand multiplatform app in Brazil",
      "company": "HXD Smart Solutions",
      "role": "Full Stack Engineer",
    },
    "year": 2013,
    "platforms": "Samsung SmartTV OS,LG SmartTV OS,Web",
    "stack": "JavaScript,XML,JSON,ES6,HTML5,CSS3,UX/UI Design,i18n",
    "thumbImgUrl": "/img/portfolio/band-ip/band_thumb.jpg",
    "thumbVideoUrl": "/img/portfolio/band-ip/band_thumb.mp4",
    "thumbGifUrl": "/img/portfolio/band-ip/band_0.gif",
    "behanceUrl": "https://www.behance.net/gallery/74097179/Band-IP",
  }
}

export default PROJECTS;